---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasm
handler: wasm
---
# Source: fission-all/templates/misc-functions/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fission-function
  labels:
    name: fission-function
    chart: "fission-all-v1.17.0"
---
# Source: fission-all/templates/misc-functions/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fission-builder
  labels:
    name: fission-builder
    chart: "fission-all-v1.17.0"
---
# Source: fission-all/templates/common/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-svc
  namespace: fission
---
# Source: fission-all/templates/misc-functions/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-fetcher
  namespace: fission-function
---
# Source: fission-all/templates/misc-functions/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-builder
  namespace: fission-builder
---
# Source: fission-all/templates/controller/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-config
  namespace: fission
data:
  "config.yaml": Y2FuYXJ5OgogIGVuYWJsZWQ6IGZhbHNlCiAgcHJvbWV0aGV1c1N2YzogIiIKYXV0aDoKICBlbmFibGVkOiBmYWxzZQ==
---
# Source: fission-all/templates/common/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fission-v1-17-0-fission-cr-admin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  - serviceaccounts
  - replicationcontrollers
  - namespaces
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fission.io
  resources:
  - canaryconfigs
  - environments
  - functions
  - httptriggers
  - kuberneteswatchtriggers
  - messagequeuetriggers
  - packages
  - timetriggers
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - keda.sh
  resources:
  - scaledjobs
  - scaledobjects
  - scaledjobs/finalizers
  - scaledjobs/status
  - triggerauthentications
  - triggerauthentications/status
  verbs:
  - '*'
- apiGroups:
  - keda.k8s.io
  resources:
  - scaledjobs
  - scaledobjects
  - scaledjobs/finalizers
  - scaledjobs/status
  - triggerauthentications
  - triggerauthentications/status
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
---
# Source: fission-all/templates/misc-functions/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fission-v1-17-0-secret-configmap-getter
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - watch
      - list
---
# Source: fission-all/templates/misc-functions/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fission-v1-17-0-package-getter
rules:
  - apiGroups:
      - "*"
    resources:
      - packages
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - "*"
---
# Source: fission-all/templates/common/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-v1-17-0-fission-cr-admin
subjects:
  - kind: ServiceAccount
    name: fission-svc
    namespace: fission
roleRef:
  kind: ClusterRole
  name: fission-v1-17-0-fission-cr-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: fission-all/templates/misc-functions/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-v1-17-0-fission-fetcher
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - fission.io
    resources:
      - canaryconfigs
      - environments
      - functions
      - httptriggers
      - kuberneteswatchtriggers
      - messagequeuetriggers
      - packages
      - timetriggers
    verbs:
      - "*"
---
# Source: fission-all/templates/misc-functions/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-v1-17-0-fission-builder
  namespace: default
rules:
  - apiGroups:
      - fission.io
    resources:
      - canaryconfigs
      - environments
      - functions
      - httptriggers
      - kuberneteswatchtriggers
      - messagequeuetriggers
      - packages
      - timetriggers
    verbs:
      - "*"
---
# Source: fission-all/templates/misc-functions/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fission-function
  name: fission-v1-17-0-event-fetcher
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["events"]
    verbs: ["*"]
---
# Source: fission-all/templates/misc-functions/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fission-v1-17-0-fission-fetcher
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fission-v1-17-0-fission-fetcher
subjects:
  - kind: ServiceAccount
    name: fission-fetcher
    namespace: fission-function
---
# Source: fission-all/templates/misc-functions/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fission-v1-17-0-fission-builder
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fission-v1-17-0-fission-builder
subjects:
  - kind: ServiceAccount
    name: fission-builder
    namespace: fission-builder
---
# Source: fission-all/templates/misc-functions/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fission-v1-17-0-fission-fetcher-pod-reader
  namespace: fission-function
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fission-v1-17-0-event-fetcher
subjects:
  - kind: ServiceAccount
    name: fission-fetcher
    namespace: fission-function
---
# Source: fission-all/templates/controller/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    svc: controller
    application: fission-api
    chart: "fission-all-v1.17.0"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: controller
---
# Source: fission-all/templates/executor/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: executor
  labels:
    svc: executor
    chart: "fission-all-v1.17.0"
spec:
  type: NodePort
  ports:
    - nodePort: 32088
      port: 80
      targetPort: 8888
  selector:
    svc: executor
---
# Source: fission-all/templates/router/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    svc: router
    application: fission-router
    chart: "fission-all-v1.17.0"
spec:
  type: NodePort
  ports:
    - nodePort: 32046
      port: 80
      targetPort: 8888
  selector:
    svc: router
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: agent
#   labels:
#     svc: agent
#     application: fission-agent
#     chart: "fission-all-v1.17.0"
# spec:
#   type: NodePort
#   ports:
#     - NodePort: 32338
#       port: 80
#       targetPort: 8888
#   selector:
#     svc: agent
---
# Source: fission-all/templates/controller/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    chart: "fission-all-v1.17.0"
    svc: controller
    application: fission-api
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: controller
      application: fission-api
  template:
    metadata:
      labels:
        svc: controller
        application: fission-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: controller
        image: "amnesia1997/fission-bundle:v0.1.1"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--controllerPort", "8888"]
        env:
        - name: FISSION_FUNCTION_NAMESPACE
          value: "fission-function"
        - name: DEBUG_ENV
          value: "false"
        - name: PPROF_ENABLED
          value: "false"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace        
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: ""
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: REAPER_IDLE_POD_REAP_TIME
          value: "3m"
        resources:
          {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8888
          initialDelaySeconds: 35
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/config.yaml
          subPath: config.yaml
        ports:
          - containerPort: 8080
            name: metrics
          - containerPort: 8888
            name: http
  
      serviceAccountName: fission-svc
      volumes:
      - name: config-volume
        configMap:
          name: feature-config
---
# Source: fission-all/templates/executor/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
  labels:
    chart: "fission-all-v1.17.0"
    svc: executor
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: executor
  template:
    metadata:
      labels:
        svc: executor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: executor
        image: "amnesia1997/fission-bundle:v0.1.1"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--executorPort", "8888", "--namespace", "fission-function"]
        env:
        - name: FETCHER_IMAGE
          value: "fission/fetcher:v1.17.0"
        - name: FETCHER_IMAGE_PULL_POLICY
          value: "IfNotPresent"
        - name: RUNTIME_IMAGE_PULL_POLICY
          value: "IfNotPresent"
        - name: ADOPT_EXISTING_RESOURCES
          value: "false"
        - name: POD_READY_TIMEOUT
          value: "300s"
        - name: ENABLE_ISTIO
          value: "false"
        - name: FETCHER_MINCPU
          value: "10m"
        - name: FETCHER_MINMEM
          value: "16Mi"
        - name: FETCHER_MAXCPU
          value: ""
        - name: FETCHER_MAXMEM
          value: ""
        - name: DEBUG_ENV
          value: "false"
        - name: PPROF_ENABLED
          value: "false"
        - name: HELM_RELEASE_NAME
          value: "fission-v1-17-0"        
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: ""
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: MASTER_IP
          value: "localhost"
        - name: NODE_PORT
          value: "32088"
        resources:
          {}
        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8888
          initialDelaySeconds: 35
          periodSeconds: 5
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8888
          name: http
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccountName: fission-svc
---
# Source: fission-all/templates/router/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  labels:
    chart: "fission-all-v1.17.0"
    svc: router
    application: fission-router
spec:
  replicas: 1
  selector:
    matchLabels:
      application: fission-router
      svc: router
  template:
    metadata:
      labels:
        application: fission-router
        svc: router
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: router
        image: "amnesia1997/fission-bundle:v0.1.1"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--routerPort", "8888", "--executorUrl", "http://executor.fission"]
        env:      
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROUTER_ROUND_TRIP_TIMEOUT
          value: "50ms"
        - name: ROUTER_ROUNDTRIP_TIMEOUT_EXPONENT
          value: "2"
        - name: ROUTER_ROUND_TRIP_KEEP_ALIVE_TIME
          value: "30s"
        - name: ROUTER_ROUND_TRIP_DISABLE_KEEP_ALIVE
          value: "true"
        - name: ROUTER_ROUND_TRIP_MAX_RETRIES
          value: "10"
        - name: ROUTER_SVC_ADDRESS_MAX_RETRIES
          value: "5"
        - name: ROUTER_SVC_ADDRESS_UPDATE_TIMEOUT
          value: "30s"
        - name: ROUTER_UNTAP_SERVICE_TIMEOUT
          value: "3600s"
        - name: USE_ENCODED_PATH
          value: "false"
        - name: DEBUG_ENV
          value: "true"
        - name: PPROF_ENABLED
          value: "false"
        - name: DISPLAY_ACCESS_LOG
          value: "false"        
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: ""
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        resources:
          {}
        readinessProbe:
          httpGet:
            path: "/router-healthz"
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: "/router-healthz"
            port: 8888
          initialDelaySeconds: 35
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/config.yaml
          subPath: config.yaml
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8888
          name: http
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccountName: fission-svc
      volumes:
      - name: config-volume
        configMap:
          name: feature-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer
  labels:
    chart: "fission-all-v1.17.0"
    svc: timer
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: timer
  template:
    metadata:
      labels:
        svc: timer
    spec:
      containers:
      - name: timer
        image: "amnesia1997/fission-bundle:v0.1.1"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--timer", "--routerUrl", "http://router.fission"]
        env:
        - name: DEBUG_ENV
          value: "false"
        - name: PPROF_ENABLED
          value: "false"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: ""
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        resources:
          {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccountName: fission-svc
---
